name: Scoreboad-Info
version: '${project.version}'
main: de.keksgauner.ScoreboadInfo
api-version: 1.18
loadbefore: [ Lands ]
depend: [ Lands ]
authors: [ Keksgauner ]
description: Zeigt in Scoreboard den Plotbesitzer und die Position
website: https://cookieleaks.de
